### ISSUE TITLE
Not connecting

### ISSUE THREAD

**Issue by hotswapster** [sworisbreathing/go-ibbq#5]
Hi @sworisbreathing , 

Thank you for making your software available. I like the idea of this software and would like to use it. I'm not much of a Go man - more JS or C++ (Node-red and Arduino). I managed to get the datalogger example working to the point it says `INF main Status updated status: Connecting`, then after awhle I get `ERR ibbq timeout while connecting` followed by 
```
INF main Status updated status: Disconnected
FTL main Error connecting to device
```
The device does work with my phone. I'm using a 2012 Macbook Pro to connect to it however, the iBBQ doesn't appear in the bluetooth device list either. I've also tried removing the batteries from the device and starting again and making sure my phone bluetooth was off. The Inkbird IBT-2x I'm using has firmware rev 2.21.

If I can get this working I'd be interested in making a trending front end for it or something else that may be within my capabilities. If you could provide any suggestions to get the connection working I'd appreciate it. I also tried the web example, the webserver loaded but the connection to the device never completed.

**Comment by sworisbreathing** [comment]
_Edit: it's almost certainly caused by changes in High Sierra / Mojave. Hopefully once go-ble/ble#32 is resolved I can update the dependency version and things will work again_

Hey @hotswapster - sorry for the delayed response.

If I remember correctly, I had trouble testing the latest build of the websocket app on my 2013 MBP, even though supposedly it supports BLE. My Raspberry Pi is still running an older build and I don't remember if I'd tried that one on the MBP.

BLE support was added right around the time your Mac was built so you should probably [check it](https://superuser.com/a/703268/124513) just to be sure you have the hardware support. 

As for the device not appearing in the Bluetooth device list on the Mac, according to [this post on stackexchange](https://apple.stackexchange.com/questions/338321/macos-bluetooth-menu-bar-show-ble-devices) you need to hold down the `Option` (`Alt`) key on your keyboard when clicking the bluetooth icon on the menu bar in order for it to show BLE devices.

Related issues:
noble/noble#728 and noble/noble#679 - seems there were some changes to CoreBluetooth starting with High Sierra that broke things in the node.js BLE libraries
go-ble/ble#32, go-ble/ble#46, and ricallinson/tpms#4 - all related to changes made in Mojave that break the go library that go-ibbq uses.

**Comment by hotswapster** [comment]
Thank you for your detailed reply. I also apologise for the late reply of mine.
I must sheepishly admit I assumed my Macbook had BLE. Turns out it was the model before. Thank you for the pointers you gave.
